Frontend jim
WEEE-Open/skeeelled pull request #110
Opened 2022-05-18 16:07 UTC by itIsJim

simulation page - start simulation - simulation result

2022-05-18 16:10 UTC, e-caste requested changes
- [x] opposite time visualization (elapsed/total)
- [x] max number of questions should be 100 (invisible to the user)
- [ ] separate warnings for each invalid input
- [x] add results for each question under results table in simulation results page (you can use a `List`)

2022-05-24 17:04 UTC, e-caste requested changes

2022-05-24 17:04 UTC, e-caste commented on client/src/pages/StartSimulation.js
>    }, [userInput]);
Remember to remove this!

2022-05-24 19:22 UTC, itIsJim commented on client/src/base/List.js
> +      <Container>
I think I can do that. And for the other two, I have already fixed them. I will push them all together.

2022-06-03 08:42 UTC, e-caste approved these changes

2022-06-03 08:43 UTC, merged