ml-mod.it
WEEE-Open/skeeelled pull request #93
Opened 2022-04-20 15:05 UTC by papadeiv

Inference pipeline for machine-learning detection of toxicity and profanity content in italian and english comments.

2022-04-20 15:24 UTC, e-caste commented on ml/requirements.txt
> +zipp @ file:///tmp/build/80754af9/zipp_1633618647012/work
Requirements should only be the needed libraries to make everything work (including the scrapers), and they shouldn't contain any local file. If `conda` uses the strange `library @ file:///path` format then simply use `python3 -m venv venv` followed by `source venv/bin/activate` and `pip install <libraries>` and finally `pip freeze > requirements.txt` to get a clean requirements file.

2022-04-21 08:32 UTC, e-caste requested changes
Just a few notes until issues #91 and #92 are closed. Good job!

2022-04-21 08:32 UTC, e-caste commented on ml/Detectors.py
> +      self.vocabulary = ["merda", "cazzo", "incazzato", "stocazzo", "coglione", "minchia", "minchiata", "minchiate", "stronzo", "stronzata", "stronzate", "puttana", "puttanata", "puttanate", "vaffanc
See issue #91

2022-04-21 08:32 UTC, e-caste commented on ml/Detectors.py
> +                                         )
Could you add a bit of documentation (either in the code or in the README) as to where to find the correct hyperparameters for each model?

2022-04-21 08:32 UTC, e-caste commented on ml/Detectors.py
> +      return False # Non-Toxic
```suggestion
    return toxic > 0.5
```

2022-04-21 08:32 UTC, e-caste commented on ml/Modali.py
> +            return None
See issue #92

2022-04-21 08:32 UTC, e-caste commented on ml/Modali.py
> +  Linguist = Polyglot()
Just for the sake of clarity, variables should have a lowercase initial (while classes an uppercase one)
```suggestion
  linguist = Polyglot()
```

2022-04-21 08:32 UTC, e-caste commented on ml/test.py
> +        non_toxic += 1
Just a bit more pythonic:
```suggestion
for label, feature in zip(labels, features):
    if label is True:  # Toxic
        dataset.append({"text": str(feature), "label": toxic_id})
        toxic += 1

    elif label is False:  # Non-Toxic
        dataset.append({"text": str(feature), "label": non_toxic_id})
        non_toxic += 1
```

2022-04-21 08:32 UTC, e-caste commented on ml/test.py
> +        model_label = 0 # Non-Toxic
```suggestion
    model_label = 1 if label is True else 0
```

2022-04-23 11:25 UTC, papadeiv commented on ml/test.py
> +        non_toxic += 1
Generates empty list.

2022-04-23 12:03 UTC, papadeiv commented on ml/Modali.py
> +  Linguist = Polyglot()
Solved with [357c76b](https://github.com/WEEE-Open/skeeelled/commit/357c76b7933afd7f3243c3b1b7b8146b14bd2524).

2022-05-02 07:49 UTC, papadeiv commented on ml/Detectors.py
> +                                         )
Issue closed.

2022-05-02 13:52 UTC, e-caste approved these changes

2022-05-02 13:54 UTC, merged